In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1566, 5124, 3988, 5316],
 [1566, 5124, 3988, 4302],
 [1566, 2215, 3988, 2969],
 [1246, 248, 4606, 2759, 351],
 [1246, 248, 4606, 2759, 7900],
 [3135, 1566, 4760, 3988, 8507],
 [6412, 7144, 823, 2759]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1566 5124 3988 5316]
 [   0    0    0    0 1566 5124 3988 4302]
 [   0    0    0    0 1566 2215 3988 2969]
 [   0    0    0 1246  248 4606 2759  351]
 [   0    0    0 1246  248 4606 2759 7900]
 [   0    0    0 3135 1566 4760 3988 8507]
 [   0    0    0    0 6412 7144  823 2759]]


In [11]:
dim = 10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sumit\OneDrive\Desktop\Movie_Reviews_Prediction\movie_env\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.04082041,  0.01429422,  0.03174141,  0.0270474 ,
          0.00272651, -0.04983348,  0.01589402, -0.01819917,
          0.01310946, -0.02957584],
        [ 0.00457241,  0.01008201, -0.02479776,  0.00667212,
          0.04377529, -0.02611921, -0.04480643,  0.03816146,
          0.00713316, -0.02394536],
        [ 0.03618762, -0.02475359, -0.04363697, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 1566, 5124, 3988, 5316], dtype=int32)

In [21]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[[ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.03682819, -0.01571977, -0.01630416, -0.03136237,
          0.00447453, -0.02435316,  0.01590247,  0.01949489,
         -0.00797793, -0.03161192],
        [ 0.04082041,  0.01429422,  0.03174141,  0.0270474 ,
          0.00272651, -0.04983348,  0.01589402, -0.01819917,
          0.01310946, -0.02957584],
        [ 0.00457241,  0.01008201, -0.02479776,  0.00667212,
          0.04377529, -0.02611921, -0.04480643,  0.03816146,
          0.00713316, -0.02394536],
        [ 0.03618762, -0.02475359, -0.04363697, -0.0