In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[534, 2168, 1128, 3160],
 [534, 2168, 1128, 2711],
 [534, 7458, 1128, 2938],
 [3111, 9447, 9043, 5548, 1651],
 [3111, 9447, 9043, 5548, 6064],
 [3173, 534, 1796, 1128, 6751],
 [3127, 542, 6316, 5548]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  534 2168 1128 3160]
 [   0    0    0    0  534 2168 1128 2711]
 [   0    0    0    0  534 7458 1128 2938]
 [   0    0    0 3111 9447 9043 5548 1651]
 [   0    0    0 3111 9447 9043 5548 6064]
 [   0    0    0 3173  534 1796 1128 6751]
 [   0    0    0    0 3127  542 6316 5548]]


In [9]:
dim = 10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\sumit\OneDrive\Desktop\Movie_Reviews_Prediction\movie_env\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


array([[[-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [ 0.04712868,  0.03593523,  0.0198094 , -0.03886526,
          0.01058853, -0.00848498, -0.02954576,  0.00585747,
          0.04521377,  0.02697922],
        [-0.02129362, -0.02662872,  0.04462543, -0.00270221,
          0.00789269, -0.000887  ,  0.03320864,  0.0083367 ,
          0.04274198,  0.0214089 ],
        [-0.00435973, -0.04122833, -0.0109546 , -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0,  534, 2168, 1128, 3160], dtype=int32)

In [14]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[[-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [-0.01693689, -0.04928194,  0.02749257, -0.02495363,
          0.01930741,  0.01670749,  0.04717764, -0.02259021,
          0.01071882,  0.0410357 ],
        [ 0.04712868,  0.03593523,  0.0198094 , -0.03886526,
          0.01058853, -0.00848498, -0.02954576,  0.00585747,
          0.04521377,  0.02697922],
        [-0.02129362, -0.02662872,  0.04462543, -0.00270221,
          0.00789269, -0.000887  ,  0.03320864,  0.0083367 ,
          0.04274198,  0.0214089 ],
        [-0.00435973, -0.04122833, -0.0109546 , -0.0